### PR TITLE
fix(kurento.css): remove `body`

### PR DESCRIPTION
**Pull request by pahaz**

### CODE REVIEW

**Comment by igracia** [comment]
@pahaz Could you please provide some feedback about this pull request?

**Comment by rosswilson** [comment]
@igracia What feedback is required? This PR corrects a simple CSS mistake, literally a one-line fix.

**Comment by igracia** [comment]
@pahaz Yeah sorry, pretty dumb question. Don't know what I was thinking...

**Comment by pahaz** [comment]
What about merge?

**Pull request closed without merging**
